objects=\
cg.o\
compute_A_x.o\
compute_confidence_map.o\
compute_depth_confidence.o\
compute_preconditioner.o\
domain_transform_recursive_filter.o\
domain_transform_recursive_filter_dmag9b.o\
fast_bilateral_solver.o\
gradient_x.o\
gradient_y.o\
hash_table_get_vert.o\
hash_table_insert_vert.o\
mesh_create_vert.o\
mesh_free.o\
mesh_new.o\
mesh_vert_get_data.o\
normalize_image.o\
pcg.o\
robust_bilateral_solver.o\
stereo_build_Cn_Cs_matrix.o\
stereo_create_verts.o\
transformed_domain_recursive_filter_horizontal.o\
transformed_domain_recursive_filter_vertical.o
